# Generated by Django 5.2.7 on 2025-11-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identity',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student')], default='Student', max_length=10, verbose_name='Identity'),
        ),
    ]
