# Generated by Django 5.2.7 on 2025-11-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_person_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="password",
            field=models.CharField(
                default="#", max_length=128, verbose_name="Password"
            ),
        ),
    ]
