# Generated by Django 5.2.7 on 2025-12-07 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("credits", models.IntegerField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("graduate", "Graduate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="is_prerequisite_for",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrerequisiteGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_groups",
                        to="courses.course",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        related_name="prerequisite_groups_items", to="courses.course"
                    ),
                ),
            ],
        ),
    ]
