# Generated by Django 5.2.7 on 2025-12-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.IntegerField()),
                ("tag", models.CharField(default="Untagged", max_length=255)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "required_document_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="Pending Review", max_length=50)),
                (
                    "review_comment",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
